### ISSUE TITLE
simple-exec/0077-misc.c: problematic calloc prototype signature

### ISSUE THREAD

**Issue by cznic** [c-testsuite/c-testsuite#22]
[simple-exec/0077-misc.c:2:](https://github.com/c-testsuite/c-testsuite/blob/612beb65dff49773e35a77b1cda580565139bca2/tests/simple-exec/0077-misc.c#L2) `int *calloc(int, int);`

I think the signature is not correct. The Linux man pages say

```c
#include <stdlib.h>

void *calloc(size_t nelem, size_t elsize);
```

I realize the intent is to not require the preprocessor, but the C99 standard says in "6.5.2.2 Function calls":

> 2 If the expression that denotes the called function has a type that includes a prototype, the
> number of arguments shall agree with the number of parameters. Each argument shall
> have a type such that its value may be assigned to an object with the unqualified version
> of the type of its corresponding parameter.

ccgo follows the standard in this particular case faithfully so it generates code that leads to "link-time" (actually Go compile time typecheck) errors

```
#/tmp/ccgo-linker-348620017/main.go:118:58: cannot use int32(64) (type int32) as type uint64 in argument to crt.Xcalloc
#/tmp/ccgo-linker-348620017/main.go:118:69: cannot use int32(4) (type int32) as type uint64 in argument to crt.Xcalloc
```

Without the possibility to include the proper prototype, I think the closest to correct alternative would be probably

```c
void *calloc(unsigned long, unsigned long);
```

because that's what `size_t` is typedef'ed to on many, if not most platforms. It should work properly even across 32/64 bit systems.

WDYT?

edit: formatting

**Comment by alexfru** [comment]
@cznic, size_t=unsigned long will definitely be wrong on 16-bit CPUs. It may also be wrong on 32-bit ones (if long is 64-bit).
The right thing to do is to include the appropriate header and, perhaps, separate this test from those not using the standard library.
Or, one could just get rid of calloc() here.

**Comment by cznic** [comment]
> size_t=unsigned long will definitely be wrong on 16-bit CPUs. It may also be wrong on 32-bit ones (if long is 64-bit).

That's correct, however, the test suite is executed on a particular (cloud?) platform or possibly more than one particular platforms. Then the concern reduces to the question of whether aliasing `size_t` and `unsigned long` is correct for that particular platform or those particular platforms. I believe this simplification is justified by, as I presume, that the tests provided by this project are not supposed to be run by third parties on arbitrary platforms. In such case including the `<stdlib.h>` header is probably the only portable and correct solution. Either way it will make ccgo pass the `0077-misc.c` test case and make me happy ;-)

**Comment by andrewchambers** [comment]
Yeah, the root cause is the tests were just a dump of what I had in my 64 bit linux only test cases.

Right now I am working on the 'tag' mechanism for sorting tests, which may help with some of the platform stuff. I am fine with a tag for 'requires cpp',  'requires libc'. One thing I'm less sure of is how bit width of integers and pointers are related, or how I should classify those in a useful way. In general a test that is specific to amd64 or 64bit pointers or whatever should be tagged as such.

Soon I will be removing all tests and adding them back one at a time (plus some new ones) while attempting to classify them. This will probably happen in a branch.

**Comment by andrewchambers** [comment]
@alexfru a 16 bit platform would act like a test case for this test suite. The tools and suite can test each other. I know at least one other developer interested in a 16 bit platform - http://www.simple-cc.org/

**Comment by andrewchambers** [comment]
@cznic  @alexfru 

In the search branch you can now add skip scripts that look like:

```
./scripts/search-tests "not (arch=x86_64 or arch=portable) or needs-libc"
```

So the CI might not cater to everyone, but people using the repo to run their own tests can definitely filter things out.
